SEED: 101
WANDB_API_KEY: bdc8857f9d6f7010cff35bcdc0ae9413e05c75e1

project_name: federated-pet
dir_name: runs/unlearning-harmonization-unet-iffn
name: Unlearning Harmonization with IFFN+UNet

datamodule:
    root_dir: ./data/PET-EARL/foundation-dataset
    split_config: 
    - [60, 15]
    - [60, 15]
    - [60, 15]
    batch_size: 64
    patch_size: [5, 64, 64]
    num_workers: 16
    queue_max_length: 9000
    samples_per_volume: 350


unet:
    in_ch: 5
    out_ch: 5
    spatial_dims: 2
    hid_chs: [64, 128, 256, 512]
    kernel_sizes: [3, 3, 3, 3]
    strides: [1, 2, 2, 2]
    temb_channels: null
    deep_supervision: false
    use_res_block: true
    estimate_variance: false
    use_self_conditioning: false
    dropout: 0.
    learnable_interpolation: true
    use_attention: none
    num_res_blocks: 1

    act_name:
    - swish
    - {}

    norm_name:
    - group
    - {num_groups: 32, affine: true}


feature_extractor:
    input_shape: [64, 64]
    input_channels: 5
    output_channels: 5
    spatial_dims: 2
    hidden_channels: [64, 128, 256]
    kernel_sizes: [3, 3, 3]
    strides: [2, 1, 1]
    use_residual_block: true
    learnable_interpolation: true
    use_attention: none
    num_residual_blocks: 1

domain_classifier:
    num_domains: 3  # 0=a100, 1=chb, 2=rennes
    spatial_dims: 2
    hid_chs: [64, 128, 256, 256]
    kernel_sizes: [3, 3, 3, 3]
    strides: [1, 2, 2, 2]
    dropout: 0.

# Pipeline UnlearningUNet
pipeline:
    num_domains: 3
    warmup_epochs: 0.4
    max_epochs: 10

    beta_confusion: 1.0
    k_conf_steps: 1

    lambda_composite: 0.1

    lr_main:       1.0e-4
    lr_dm:         1.0e-4   # lr de départ du classifieur
    lr_dm_final:   1.0e-6   # lr final du classifieur en fin de stage 2
    lr_conf:       1.0e-6   # lr de départ de la confusion
    lr_conf_final: 5.0e-5   # lr final de la confusion en fin de stage 2         
    
    weight_decay:  1.0e-5
    suv_global_log_max: 6.0

model_checkpoint:
    monitor: val/composite_score
    every_n_epochs: 1
    save_last: true
    save_top_k: 3
    mode: min
    verbose: true
    filename: "epoch={epoch:03d}-task={val/task_loss:.4f}-dm_acc={val/domain_acc:.3f}"
    auto_insert_metric_name: false

trainer:
    precision: 16-mixed
    accelerator: gpu
    devices: 1
    log_every_n_steps: 1
    min_epochs: 2
    max_epochs: 10
    check_val_every_n_epoch: 1
    num_sanity_val_steps: 0
    limit_train_batches: 400
    limit_val_batches: 100
    # gradient_clip_val et gradient_clip_algorithm incompatibles
    # avec optimisation manuelle (multi-optimiseurs) — clip_grad_norm_
    # est appliqué manuellement dans training_step
