SEED: 101
WANDB_API_KEY: bdc8857f9d6f7010cff35bcdc0ae9413e05c75e1

project_name: federated-pet
dir_name: runs/unlearning-harmonization-unet-skip
name: Unlearning Harmonization UNet + FFT + CascadeDomainClassifier

datamodule:
    root_dir: ./data/PET-EARL/foundation-dataset
    split_config:
    - [0, 50]
    - [0, 50]
    - [0, 50]
    batch_size: 64
    patch_size: [5, 64, 64]
    num_workers: 16
    queue_max_length: 9000
    samples_per_volume: 350


unet:
    input_shape: [64, 64]
    fft_sigma: 7.5
    in_ch: 5
    out_ch: 5
    spatial_dims: 2
    hid_chs: [64, 128, 256, 512]
    kernel_sizes: [3, 3, 3, 3]
    strides: [1, 2, 2, 2]
    temb_channels: null
    use_res_block: true
    dropout: 0.
    learnable_interpolation: true
    use_attention: none
    num_res_blocks: 1

    act_name:
        - swish
        - {}

    norm_name:
        - group
        - {num_groups: 32, affine: true}

pipeline:
    num_domains: 3
    classifier_hidden_dim: 256
    warmup_epochs: 0.25 # fraction of an epoch

    # Poids de confusion loss — monte de beta_confusion vers beta_max (cosine)
    beta_confusion: 0.8
    beta_max: 1.2

    lr_dm_min_factor: 0.25
    k_conf_steps: 2
    lambda_composite: 0.1

    # Doit correspondre à trainer.max_epochs
    max_epochs: 50

    lr_main: 1.0e-4
    lr_dm: 5.0e-5
    lr_conf: 5.0e-5
    weight_decay: 1.0e-7
    suv_global_log_max: 6.0

# =============================================================================
# Checkpoint
# =============================================================================
model_checkpoint:
    monitor: val/composite_score
    every_n_epochs: 1
    save_last: true
    save_top_k: 3
    mode: min
    verbose: true
    filename: "epoch={epoch:03d}-task={val/task_loss:.4f}-dm_acc={val/domain_acc:.3f}"
    auto_insert_metric_name: false

# =============================================================================
# Trainer
# =============================================================================
trainer:
    precision: 32
    accelerator: gpu
    devices: 1
    log_every_n_steps: 1
    min_epochs: 10
    max_epochs: 120
    check_val_every_n_epoch: 1
    num_sanity_val_steps: 0
    limit_train_batches: 400
    limit_val_batches: 80
    # gradient_clip_val et gradient_clip_algorithm incompatibles
    # avec optimisation manuelle (multi-optimiseurs) — clip_grad_norm_
    # est appliqué manuellement dans training_step
