SEED: 101
WANDB_API_KEY: bdc8857f9d6f7010cff35bcdc0ae9413e05c75e1

project_name: federated-pet
dir_name: runs/harmonization-std-vae # runs/unlearning-harmonization-vae
name: Unlearning Harmonization with a Std VAE (Ablation) # StyleVAE+AdaIN Conf2 (4 Domains)

datamodule:
    root_dir: ./data/PET-EARL/
    split_config: 
<<<<<<< Updated upstream
    - [50, 15]           
    - [50, 15]           
    - [50, 15]           
    - [50, 15] 
=======
    - [60, 15]           
    - [60, 15]           
    - [60, 15]           
    - [60, 15] 
>>>>>>> Stashed changes
    batch_size:         64
    patch_size:         [5, 64, 64]
    num_workers:        16
    queue_max_length:   9000
    samples_per_volume: 350

vae:
    input_shape:          [64, 64]   # (H, W) pour FFTHighPassFilter
    fft_sigma:            7.5        # sigma du filtre gaussien passe-haut
    in_channels:          5
    out_channels:         5
    hidden_channels:      [64, 128, 256, 512]
    kernel_sizes:         [3, 3, 3, 3]
    strides:              [1, 2, 2, 2]
    latent_channels:      6
    style_channels:       256
    style_embedding_dim:  256      # aligné sur style_channels (pas d'upscaling)
    num_residual_blocks:  1
    spatial_dims:         2
    normalization:
    - group
    - {num_groups: 32, affine: true}
    activation:
    - swish
    - {}
    dropout:              0.0
    use_residual_block:   true
    learnable_interpolation: true
    attention_type:       none   
    use_contour_skip:     false


pipeline:
    num_domains:           3
    classifier_hidden_dim: 256
    warmup_epochs:         5        # stage 1 : apprendre la tâche + classifieurs

    beta_confusion:        1.0      # poids confusion loss (désapprentissage z_content)
    kl_content_weight:     5.0e-7   # régularisation KL sur z_content spatial
    kl_style_weight:       5.0e-7   # régularisation KL sur z_style 1D
    max_epochs:            70

    lr_vae:                1.0e-4   # LR reconstruction
    lr_classifiers:        1.0e-4   # LR classifieurs
    lr_classifiers_final:  1.0e-6   # LR classifieurs (plus faible : désapprentissage doux)
    lr_unlearn:            1.0e-6   # LR confusion (plus faible : désapprentissage doux)
    lr_unlearn_final:      5.0e-6
    k_style_steps:         1        # nombre d'itérations de mise à jour du style par étape d'entraînement

    weight_decay:          1.0e-6
    suv_global_log_max:    6.0


model_checkpoint:
    monitor: val/composite_score
    every_n_epochs: 1
    save_last: true
    save_top_k: 3
    mode: min
    verbose: true
    filename: "epoch={epoch:03d}-rec={val/rec_loss:.4f}-style={val/style_acc:.3f}-content={val/content_acc:.3f}"
    auto_insert_metric_name: false

trainer:
    precision:           32
    accelerator:         gpu
    devices:             1
    log_every_n_steps:   1
    min_epochs:          10
    max_epochs:          120
    check_val_every_n_epoch: 1
    num_sanity_val_steps: 0
    limit_train_batches: 400
    limit_val_batches:   80

    # Non compatible avec optimisation manuelle (multi-optimiseurs)
    # gradient_clip_val: 1.0
    # gradient_clip_algorithm: "norm"

    
